export const works = [
  {
    id: "bascorp-brand",
    name: "Bascorp",
    slug: "bascorp",
    type: "product",
    description: "Brand identity and digital product design.",
    categories: ["Brand Identity", "Web Design", "UI/UX Design"],
    category: "Brand Identity",
    image: "/images/bascorp/header.jpg",
    width: 2400,
    height: 1600,
    position: "left",
  },

  {
    id: "petrha-group-brand",
    name: "Petrha Group",
    slug: "petrha-group",
    type: "product",
    description: "Brand identity and digital product design.",
    categories: ["Brand Identity", "Web Design", "UI/UX Design"],
    category: "Brand Identity",
    image: "/images/petrha/man.jpg",
    width: 2400,
    height: 1600,
    position: "left",
  },

  {
    id: "shine-and-shield-brand",
    name: "Shine & Shield",
    slug: "shine-and-shield",
    type: "product",
    description: "Brand identity",
    categories: ["Brand Identity"],
    category: "Brand Identity",
    image: "/images/shineshield/image-group.jpg",
    width: 2400,
    height: 1600,
    position: "left",
  },

  {
    id: "aquadro-holding-editorial",
    name: "Aquadro Holding",
    slug: "aquadro-holding",
    type: "editorial",
    description: "Desktop Publishing.",
    categories: ["Editorial Design", "Typography"],
    category: "Editorial & DTP",
    image: "/images/editorial/aquadro-brochure.jpg",
    position: "left",
    width: 100,
    height: 500,
  },

  {
    id: "a-christmas-carol-editorial",
    name: "A Christmas Carol",
    slug: "a-christmas-carol",
    type: "editorial",
    description: "Editorial design and typography.",
    categories: ["Editorial Design", "Typography"],
    category: "Editorial & DTP",
    image: "/images/editorial/book/capitolo.jpg",
    position: "right",
    width: 100,
    height: 500,
  },

  {
    id: "cultural-magazine-editorial",
    name: "Cultural Magazine",
    slug: "cultural-magazine",
    type: "editorial",
    description: "Editorial design and typography.",
    categories: ["Editorial Design", "Typography"],
    category: "Editorial & DTP",
    image: "/images/editorial/magazine/magazine_1.jpg",
    position: "left",
    width: 100,
    height: 500,
  },

  {
    id: "bird-watching-logbook-editorial",
    name: "Bird Watching Logbook",
    slug: "bird_watching_logbook",
    type: "editorial",
    description: "Editorial design and typography.",
    categories: ["Editorial Design", "Typography"],
    category: "Editorial & DTP",
    image: "/images/editorial/bird_logbook.jpg",
    position: "left",
    width: 100,
    height: 500,
  },

  {
    id: "social-media-campaign",
    name: "Social Media Campaign",
    slug: "social-media-campaign",
    type: "social-media",
    description: "Social media content creation and management.",
    categories: ["Social Media", "Content Creation"],
    category: "Social Media",
    image: "/images/editorial/magazine/IG_feed.jpg",
    position: "right",
    width: 100,
    height: 500,
  },

  {
    id: "bascorp-social-media",
    name: "Bascorp",
    slug: "bascorp",
    type: "social-media",
    description: "Social media content creation and management.",
    categories: ["Social Media", "Content Creation"],
    category: "Social Media",
    image: "/images/bascorp/ig.jpg",
    position: "right",
    width: 100,
    height: 500,
  },

  {
    id: "aquadro-holding-social-media",
    name: "Aquadro Holding",
    slug: "aquadro-holding",
    type: "social-media",
    description: "Social media content creation and management.",
    categories: ["Social Media", "Content Creation"],
    category: "Social Media",
    image: "/images/aquadro/ig_feed.jpg",
    position: "right",
    width: 100,
    height: 500,
  },

  {
    id: "bascorp-graphic-design",
    name: "Bascorp",
    slug: "bascorp",
    type: "graphic-design",
    description: "Graphic design work.",
    categories: ["Graphic Design"],
    category: "Graphic Design",
    image: "/images/bascorp/poster.png",
    position: "right",
    width: 100,
    height: 500,
  },

  {
    id: "petrha-group-graphic-design",
    name: "Petrha Group",
    slug: "petrha-group",
    type: "graphic-design",
    description: "Graphic design work.",
    categories: ["Graphic Design"],
    category: "Graphic Design",
    image: "/images/petrha/businesscard.jpg",
    position: "right",
    width: 100,
    height: 500,
  },

  {
    id: "boeing-poster",
    name: "Boeing Poster",
    slug: "boeing-poster",
    type: "graphic-design",
    description: "Graphic design work.",
    categories: ["Graphic Design"],
    category: "Graphic Design",
    image: "/images/misc/boeing.jpg",
    position: "right",
    width: 100,
    height: 500,
  },

  {
    id: "campaign-poster",
    name: "Campaign Poster",
    slug: "campaign-poster",
    type: "graphic-design",
    description: "Graphic design work.",
    categories: ["Graphic Design"],
    category: "Graphic Design",
    image: "/images/loud/group.jpg",
    position: "right",
    width: 100,
    height: 500,
  },

  {
    id: "bascorp-web-design",
    name: "Bascorp Web Design Project",
    slug: "bascorp",
    type: "web-design",
    description: "Web design work.",
    categories: ["Web Design"],
    category: "Web Design",
    image: "/images/bascorp/site.jpg",
    position: "right",
    width: 100,
    height: 500,
  },

  {
    id: "tydedev-web-design",
    name: "Tydedev Web Design Project",
    slug: "web-design-project",
    type: "web-design",
    description: "Web design work.",
    categories: ["Web Design"],
    category: "Web Design",
    image: "/images/web-design/tydedev.png",
    position: "right",
    width: 100,
    height: 500,
  },

  {
    id: "typelier-web-design",
    name: "Typelier Web Design Project",
    slug: "web-design-project",
    type: "web-design",
    description: "Web design work.",
    categories: ["Web Design"],
    category: "Web Design",
    image: "/images/web-design/typelier.png",
    position: "right",
    width: 100,
    height: 500,
  },
];
